### ISSUE TITLE
Invalid input is not filtered with non-native pickers

### ISSUE THREAD

**Issue by lpellegr** [fooloomanzoo/datetime-picker#7]
It is possible to enter invalid inputs.

![screenshot from 2017-08-06 12-30-26](https://user-images.githubusercontent.com/128898/29002456-3f2db482-7aa3-11e7-8c4f-d403236457f6.png)

![screenshot from 2017-08-06 12-30-44](https://user-images.githubusercontent.com/128898/29002459-436806b0-7aa3-11e7-861a-aa81f0d06234.png)

Such inputs should have no effects as for the native pickers.

**Comment by fooloomanzoo** [comment]
should be fixed: https://github.com/fooloomanzoo/datetime-picker/releases/tag/2.0.5

**Comment by lpellegr** [comment]
@fooloomanzoo It is not fixed. For instance, press `e` on any non-native picker:

![screenshot from 2017-08-07 21-36-18](https://user-images.githubusercontent.com/128898/29042762-8e2f584a-7bb8-11e7-9fed-1dfb4fd7af46.png)

![screenshot from 2017-08-07 21-36-27](https://user-images.githubusercontent.com/128898/29042760-8c0e7028-7bb8-11e7-8741-177cc67d5b93.png)

**Comment by fooloomanzoo** [comment]
_e_ is part of a Number representation like _,_ or _._ too. The inputs are now of `type="number"` instead of using the `pattern` attribute and a `regexp` like before. But testing if something is a valid date, will always cause when failing to fall back to the last value. This won't cause that a new value is generated, so it might not be worth to find a complete new logic, or you would try your luck finding a nice and easy solution
